remote_theme: pages-themes/lagrange@main

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

title: "Daft Punk Blog"
description: "Daft Punk, lo mejor de la música house"
author: "Erick Daniel"
url: "https://erick-amasonense.github.io/Lagrange"

paginate: 5
markdown: kramdown
highlighter: rouge
